project_id = "qrpacpoxwewjzbsdjzai"

[functions.n8n-daily-orders]
verify_jwt = false

[functions.update-nfe]
verify_jwt = false

[functions.brewery-webhook]
verify_jwt = false

[functions.master-organizations]
verify_jwt = true
