project_id = "qrpacpoxwewjzbsdjzai"

[functions.n8n-daily-orders]
verify_jwt = false

[functions.update-nfe]
verify_jwt = false

[functions.brewery-webhook]
verify_jwt = false

[functions.master-organizations]
verify_jwt = true

[functions.master-integrations]
verify_jwt = true

[functions.barrel-inventory-control]
verify_jwt = true

[functions.organization-users]
verify_jwt = true

[functions.onboarding-imports]
verify_jwt = true
