import { useState } from 'react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { useBeerTypes } from '@/hooks/useEquipment';
import { useBarrelModels } from '@/hooks/useBarrelInventory';
import { remainingBreweryItem, useBreweryOrders, useCreateBreweryOrder, useReceiveBreweryItem, useSendBreweryOrder } from '@/hooks/useBreweryOrders';
import { BreweryOrderItem, BreweryOrderStatus } from '@/types/database';
import { Plus, Send, Truck } from 'lucide-react';

const labels:Record<BreweryOrderStatus,string>={draft:'Rascunho',pending_send:'Aguardando envio',sent:'Enviado',acknowledged:'Recebido pela cervejaria',confirmed:'Confirmado',released:'Liberado/faturado',in_transit:'Em trânsito',partially_received:'Recebido parcialmente',received:'Recebido',rejected:'Rejeitado',cancelled:'Cancelado',discrepancy:'Com divergência'};
type FormItem={barrel_model_id:string;beer_type_id:string;quantity_ordered:number;unit_cost:number};
export default function BreweryOrders(){
  const {data:orders,isLoading}=useBreweryOrders(); const {data:beerTypes}=useBeerTypes(); const {data:models}=useBarrelModels(); const create=useCreateBreweryOrder(); const send=useSendBreweryOrder(); const receive=useReceiveBreweryItem();
  const [open,setOpen]=useState(false); const [items,setItems]=useState<FormItem[]>([{barrel_model_id:'',beer_type_id:'',quantity_ordered:1,unit_cost:0}]); const [receiveItem,setReceiveItem]=useState<BreweryOrderItem|null>(null);
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await create.mutateAsync({supplier:String(f.get('supplier')),expected_delivery_date:String(f.get('expected_delivery_date')||'')||null,notes:String(f.get('notes')||'')||null,items});setOpen(false);setItems([{barrel_model_id:'',beer_type_id:'',quantity_ordered:1,unit_cost:0}]);};
  return <MainLayout><div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold">Pedidos à cervejaria</h1><p className="text-muted-foreground">Acompanhe solicitação, liberação, trânsito e recebimento físico.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="mr-2 h-4 w-4"/>Novo pedido</Button></DialogTrigger><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Novo pedido à cervejaria</DialogTitle></DialogHeader><form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div><Label>Cervejaria *</Label><Input name="supplier" required/></div><div><Label>Previsão de entrega</Label><Input name="expected_delivery_date" type="date"/></div></div>{items.map((item,i)=><div key={i} className="grid gap-3 border-b pb-3 sm:grid-cols-4"><div><Label>Barril *</Label><Select value={item.barrel_model_id} onValueChange={v=>{const n=[...items];n[i].barrel_model_id=v;setItems(n)}}><SelectTrigger><SelectValue placeholder="Volume"/></SelectTrigger><SelectContent>{models?.map(m=><SelectItem key={m.id} value={m.id}>{m.volume}L</SelectItem>)}</SelectContent></Select></div><div><Label>Chopp *</Label><Select value={item.beer_type_id} onValueChange={v=>{const n=[...items];n[i].beer_type_id=v;setItems(n)}}><SelectTrigger><SelectValue placeholder="Tipo"/></SelectTrigger><SelectContent>{beerTypes?.map(b=><SelectItem key={b.id} value={b.id}>{b.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Quantidade *</Label><Input type="number" min="1" value={item.quantity_ordered} onChange={e=>{const n=[...items];n[i].quantity_ordered=Number(e.target.value);setItems(n)}}/></div><div><Label>Custo/barril</Label><Input type="number" min="0" step="0.01" value={item.unit_cost||''} onChange={e=>{const n=[...items];n[i].unit_cost=Number(e.target.value);setItems(n)}}/></div></div>)}<Button type="button" variant="outline" onClick={()=>setItems([...items,{barrel_model_id:'',beer_type_id:'',quantity_ordered:1,unit_cost:0}])}><Plus className="mr-2 h-4 w-4"/>Adicionar item</Button><div><Label>Observações</Label><Textarea name="notes"/></div><div className="flex justify-end"><Button disabled={create.isPending||items.some(i=>!i.barrel_model_id||!i.beer_type_id)}>Salvar rascunho</Button></div></form></DialogContent></Dialog></div>
  <Card><CardHeader><CardTitle>Pedidos</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Nº</TableHead><TableHead>Cervejaria</TableHead><TableHead>Status</TableHead><TableHead>Previsão</TableHead><TableHead>Itens</TableHead><TableHead/></TableRow></TableHeader><TableBody>{isLoading?<TableRow><TableCell colSpan={6}>Carregando...</TableCell></TableRow>:orders?.map(order=><TableRow key={order.id}><TableCell>#{order.order_number}</TableCell><TableCell>{order.supplier}</TableCell><TableCell><Badge variant={order.status==='received'?'default':'secondary'}>{labels[order.status]}</Badge>{order.invoice_number&&<div className="mt-1 text-xs">NF {order.invoice_number}</div>}</TableCell><TableCell>{order.expected_delivery_date||'—'}</TableCell><TableCell><div className="space-y-1">{order.brewery_order_items?.map(item=><div key={item.id} className="flex items-center justify-between gap-3 text-sm"><span>{item.quantity_ordered}× {item.barrel_models?.volume}L {item.beer_types?.name} ({item.quantity_received} recebidos)</span>{remainingBreweryItem(item)>0&&order.status!=='draft'&&<Button size="sm" variant="outline" onClick={()=>setReceiveItem(item)}><Truck className="mr-1 h-3 w-3"/>Receber</Button>}</div>)}</div></TableCell><TableCell>{order.status==='draft'&&<Button size="sm" onClick={()=>send.mutate(order.id)} disabled={send.isPending}><Send className="mr-2 h-4 w-4"/>Enviar</Button>}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  <Dialog open={!!receiveItem} onOpenChange={o=>!o&&setReceiveItem(null)}><DialogContent><DialogHeader><DialogTitle>Confirmar recebimento físico</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await receive.mutateAsync({itemId:receiveItem!.id,quantity:Number(f.get('quantity'))});setReceiveItem(null)}}><p className="text-sm text-muted-foreground">Esta ação movimentará os barris de “na cervejaria” para “cheio na loja”.</p><div><Label>Quantidade recebida</Label><Input name="quantity" type="number" min="1" max={receiveItem?remainingBreweryItem(receiveItem):1} defaultValue={receiveItem?remainingBreweryItem(receiveItem):1} required/></div><div className="flex justify-end"><Button disabled={receive.isPending}>Registrar entrada</Button></div></form></DialogContent></Dialog>
  </div></MainLayout>;
}
