create index barrel_inventory_org_model_idx on public.barrel_inventory (organization_id, barrel_model_id);
create index barrel_inventory_org_beer_idx on public.barrel_inventory (organization_id, beer_type_id);
create index barrels_org_unit_idx on public.barrels (organization_id, unit_id);
create index barrels_org_beer_idx on public.barrels (organization_id, beer_type_id);
create index customers_org_unit_idx on public.customers (organization_id, unit_id);
create index cylinder_inventory_org_model_idx on public.cylinder_inventory (organization_id, cylinder_model_id);
create index cylinders_org_unit_idx on public.cylinders (organization_id, unit_id);
create index order_items_org_order_idx on public.order_items (organization_id, order_id);
create index order_items_org_model_idx on public.order_items (organization_id, barrel_model_id);
create index order_items_org_beer_idx on public.order_items (organization_id, beer_type_id);
create index order_product_items_org_order_idx on public.order_product_items (organization_id, order_id);
create index order_product_items_org_product_idx on public.order_product_items (organization_id, product_id);
create index orders_created_by_idx on public.orders (created_by);
create index orders_nfe_issued_by_idx on public.orders (nfe_issued_by);
create index orders_org_unit_idx on public.orders (organization_id, unit_id);
create index orders_org_tap_idx on public.orders (organization_id, tap_id);
create index orders_org_cylinder_idx on public.orders (organization_id, cylinder_id);
create index orders_org_cylinder_model_idx on public.orders (organization_id, cylinder_model_id);
create index payments_org_order_idx on public.payments (organization_id, order_id);
create index product_movements_created_by_idx on public.product_inventory_movements (created_by);
create index product_movements_org_unit_idx on public.product_inventory_movements (organization_id, unit_id);
create index product_movements_org_order_idx on public.product_inventory_movements (organization_id, order_id);
create index products_org_unit_idx on public.products (organization_id, unit_id);
create index taps_org_unit_idx on public.taps (organization_id, unit_id);
create index taps_org_type_idx on public.taps (organization_id, tap_type_id);
